sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 'node'
  - '6'
  - '5'
  - '4'
before_install:
  - npm i -g node-pre-gyp
  - npm i -g node-gyp
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run report-coverage
